version: 2

updates:
  - package-ecosystem: "bun"
    directories:
      - "/"
      - "/example"
      - "/docs"
      - "/packages/*"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 10
    groups:
      bun-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      bun-major:
        patterns:
          - "*"
        update-types:
          - "major"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
