import type { MenuItem } from '@svadmin/core';
import { addTranslations } from '@svadmin/core';

type LocaleCode = 'en' | 'zh-CN';

type MenuNode = Omit<MenuItem, 'name' | 'icon' | 'href' | 'children'> & {
  name: MenuKey;
  icon: string;
  href?: string;
  meta?: MenuItem['meta'] & { soon?: boolean };
  children?: MenuNode[];
};

export interface ReferenceMenuCatalogRow {
  zh: string;
  en: string;
  app: string;
  level: number;
  soon: boolean;
}

export const referenceMenuCatalogRows: ReferenceMenuCatalogRow[] = [
  { zh: '仪表盘', en: 'Dashboards', app: 'Dashboards', level: 1, soon: false },
  { zh: '运营首页', en: 'Operations Dashboard', app: 'Dashboards', level: 2, soon: false },
  { zh: '个人资料', en: 'Public Profile', app: 'Public Profile', level: 1, soon: false },
  { zh: '资料概览', en: 'Overview', app: 'Public Profile', level: 2, soon: false },
  { zh: '项目', en: 'Projects', app: 'Public Profile', level: 2, soon: false },
  { zh: '两栏项目', en: '2 Columns', app: 'Public Profile', level: 3, soon: false },
  { zh: '三栏项目', en: '3 Columns', app: 'Public Profile', level: 3, soon: false },
  { zh: '活动', en: 'Activity', app: 'Public Profile', level: 2, soon: false },
  { zh: '团队', en: 'Teams', app: 'Public Profile', level: 2, soon: false },
  { zh: '资料变体', en: 'Profile Variants', app: 'Public Profile', level: 2, soon: false },
  { zh: '默认资料', en: 'Default Profile', app: 'Public Profile', level: 3, soon: false },
  { zh: '企业资料', en: 'Company Profile', app: 'Public Profile', level: 3, soon: false },
  { zh: '玩家资料', en: 'Gamer Profile', app: 'Public Profile', level: 3, soon: false },
  { zh: '我的账户', en: 'Account', app: 'Account', level: 1, soon: false },
  { zh: '账户首页', en: 'Account Home', app: 'Account', level: 2, soon: false },
  { zh: '开始使用', en: 'Get Started', app: 'Account', level: 3, soon: false },
  { zh: '用户资料', en: 'User Profile', app: 'Account', level: 3, soon: false },
  { zh: '公司资料', en: 'Company Profile', app: 'Account', level: 3, soon: false },
  { zh: '账户设置', en: 'Settings', app: 'Account', level: 2, soon: false },
  { zh: '账户设置', en: 'Account Settings', app: 'Account', level: 3, soon: false },
  { zh: '纯净设置', en: 'Settings - Plain', app: 'Account', level: 3, soon: false },
  { zh: '侧边栏设置', en: 'Settings - Sidebar', app: 'Account', level: 3, soon: false },
  { zh: '企业设置', en: 'Settings - Enterprise', app: 'Account', level: 3, soon: false },
  { zh: '外观', en: 'Appearance', app: 'Account', level: 3, soon: false },
  { zh: '通知设置', en: 'Notifications', app: 'Account', level: 3, soon: false },
  { zh: '集成', en: 'Integrations', app: 'Account', level: 3, soon: false },
  { zh: 'API 密钥', en: 'API Keys', app: 'Account', level: 3, soon: false },
  { zh: '账单', en: 'Billing', app: 'Account', level: 2, soon: false },
  { zh: '套餐方案', en: 'Plans', app: 'Account', level: 3, soon: false },
  { zh: '账单历史', en: 'Billing History', app: 'Account', level: 3, soon: false },
  { zh: '订阅', en: 'Subscriptions', app: 'Account', level: 3, soon: false },
  { zh: '成员', en: 'Members', app: 'Account', level: 2, soon: false },
  { zh: '成员入门', en: 'Members Starter', app: 'Account', level: 3, soon: false },
  { zh: '团队成员', en: 'Team Members', app: 'Account', level: 3, soon: false },
  { zh: '导入成员', en: 'Import Members', app: 'Account', level: 3, soon: false },
  { zh: '安全', en: 'Security', app: 'Account', level: 2, soon: false },
  { zh: '安全日志', en: 'Security Log', app: 'Account', level: 3, soon: false },
  { zh: '当前会话', en: 'Sessions', app: 'Account', level: 3, soon: false },
  { zh: '设备管理', en: 'Devices', app: 'Account', level: 3, soon: false },
  { zh: '允许的 IP', en: 'Allowed IPs', app: 'Account', level: 3, soon: false },
  { zh: '邀请好友', en: 'Invite a Friend', app: 'Account', level: 2, soon: false },
  { zh: '团队网络', en: 'Network', app: 'Network', level: 1, soon: false },
  { zh: '用户卡片', en: 'User Cards', app: 'Network', level: 2, soon: false },
  { zh: 'NFT 卡片', en: 'NFT Cards', app: 'Network', level: 3, soon: false },
  { zh: '用户表格', en: 'User Table', app: 'Network', level: 2, soon: false },
  { zh: '团队成员表', en: 'Team Crew', app: 'Network', level: 3, soon: false },
  { zh: '系统页面', en: 'Auth & Security', app: 'Auth & Security', level: 1, soon: false },
  { zh: '登录流程', en: 'Authentication Flow', app: 'Auth & Security', level: 2, soon: false },
  { zh: '登录页', en: 'Sign In', app: 'Auth & Security', level: 3, soon: false },
  { zh: '注册页', en: 'Sign Up', app: 'Auth & Security', level: 3, soon: false },
  { zh: '找回密码', en: 'Forgot Password', app: 'Auth & Security', level: 3, soon: false },
  { zh: '重置密码', en: 'Reset Password', app: 'Auth & Security', level: 3, soon: false },
  { zh: '两步验证', en: 'Two-Factor Auth', app: 'Auth & Security', level: 2, soon: false },
  { zh: '错误页面', en: 'Error Pages', app: 'Auth & Security', level: 2, soon: false },
  { zh: '404 页面', en: 'Error 404', app: 'Auth & Security', level: 3, soon: false },
  { zh: '500 页面', en: 'Error 500', app: 'Auth & Security', level: 3, soon: false },
  { zh: '应用', en: 'Apps', app: 'Apps', level: 1, soon: false },
  { zh: '库存中心', en: 'Inventory', app: 'Apps', level: 2, soon: false },
  { zh: '库存驾驶舱', en: 'Inventory Dashboard', app: 'Apps', level: 3, soon: false },
  { zh: '目录资料', en: 'Catalog', app: 'Apps', level: 3, soon: false },
  { zh: '商品档案', en: 'Products', app: 'Apps', level: 4, soon: false },
  { zh: 'SKU 管理', en: 'SKU Management', app: 'Apps', level: 4, soon: false },
  { zh: '品类管理', en: 'Categories', app: 'Apps', level: 4, soon: false },
  { zh: '供应商', en: 'Suppliers', app: 'Apps', level: 3, soon: false },
  { zh: '仓库', en: 'Warehouses', app: 'Apps', level: 3, soon: false },
  { zh: '客户', en: 'Customer', app: 'Apps', level: 3, soon: false },
  { zh: '库存设置', en: 'Inventory Settings', app: 'Apps', level: 3, soon: false },
  { zh: '运营作业', en: 'Operations', app: 'Apps', level: 2, soon: false },
  { zh: '库存流水', en: 'Stock Movements', app: 'Apps', level: 3, soon: false },
  { zh: '库存调拨', en: 'Stock Transfers', app: 'Apps', level: 3, soon: false },
  { zh: '循环盘点', en: 'Cycle Counts', app: 'Apps', level: 3, soon: false },
  { zh: '库存调整', en: 'Inventory Adjustments', app: 'Apps', level: 3, soon: false },
  { zh: '补货规则', en: 'Reorder Rules', app: 'Apps', level: 3, soon: false },
  { zh: '采购订单', en: 'Purchase Orders', app: 'Apps', level: 3, soon: false },
  { zh: '销售订单', en: 'Sales Orders', app: 'Apps', level: 3, soon: false },
  { zh: '用户管理', en: 'User Management', app: 'Apps', level: 2, soon: false },
  { zh: '用户', en: 'Users', app: 'Apps', level: 3, soon: false },
  { zh: '角色', en: 'Roles', app: 'Apps', level: 3, soon: false },
  { zh: '权限', en: 'Permissions', app: 'Apps', level: 3, soon: false },
  { zh: '用户账户', en: 'User Accounts', app: 'Apps', level: 3, soon: false },
  { zh: '日志', en: 'Logs', app: 'Apps', level: 3, soon: false },
  { zh: '用户策略', en: 'User Policies', app: 'Apps', level: 3, soon: false },
  { zh: '计划日程', en: 'Planning', app: 'Apps', level: 2, soon: false },
  { zh: '日历', en: 'Calendar', app: 'Apps', level: 3, soon: false },
  { zh: '待办清单', en: 'Todo Lists', app: 'Apps', level: 3, soon: false },
  { zh: '待办事项', en: 'Todo', app: 'Apps', level: 4, soon: false },
  { zh: '今日', en: 'Today', app: 'Apps', level: 4, soon: false },
  { zh: '即将到来', en: 'Upcoming', app: 'Apps', level: 4, soon: false },
  { zh: '优先级', en: 'Priority', app: 'Apps', level: 4, soon: false },
  { zh: '已完成', en: 'Completed', app: 'Apps', level: 4, soon: false },
  { zh: '标签', en: 'Tags', app: 'Apps', level: 4, soon: false },
  { zh: '智能助手', en: 'AI Assistant', app: 'Apps', level: 2, soon: false },
  { zh: '新建对话', en: 'New Chat', app: 'Apps', level: 3, soon: false },
  { zh: 'AI 对话', en: 'AI Chat', app: 'Apps', level: 3, soon: false },
  { zh: '模板', en: 'Templates', app: 'Apps', level: 3, soon: false },
  { zh: 'AI 设置', en: 'AI Settings', app: 'Apps', level: 3, soon: false },
  { zh: '消息通知', en: 'Notifications & Mail', app: 'Apps', level: 2, soon: false },
  { zh: '通知中心', en: 'Notification Center', app: 'Apps', level: 3, soon: false },
  { zh: '邮件', en: 'Mail', app: 'Apps', level: 3, soon: false },
  { zh: '收件箱', en: 'Inbox', app: 'Apps', level: 4, soon: false },
  { zh: '草稿箱', en: 'Drafts', app: 'Apps', level: 4, soon: false },
  { zh: '已发送', en: 'Sent', app: 'Apps', level: 4, soon: false },
  { zh: '归档', en: 'Archive', app: 'Apps', level: 4, soon: false },
  { zh: '邮件设置', en: 'Mail Settings', app: 'Apps', level: 4, soon: false },
  { zh: '客户经营', en: 'CRM', app: 'Apps', level: 2, soon: false },
  { zh: 'CRM 仪表盘', en: 'CRM Dashboard', app: 'Apps', level: 3, soon: false },
  { zh: '客户账户', en: 'Customer Accounts', app: 'Apps', level: 3, soon: false },
  { zh: '客户联系人', en: 'Customer Contacts', app: 'Apps', level: 3, soon: false },
  { zh: '收入机会', en: 'Revenue Opportunities', app: 'Apps', level: 3, soon: false },
  { zh: '客户活动', en: 'Customer Activities', app: 'Apps', level: 3, soon: false },
  { zh: '报表', en: 'Reports', app: 'Apps', level: 3, soon: false },
  { zh: '资产运营', en: 'Real Estate', app: 'Apps', level: 2, soon: false },
  { zh: '地图视图', en: 'Map View', app: 'Apps', level: 3, soon: false },
  { zh: '资产组合', en: 'Property Portfolio', app: 'Apps', level: 3, soon: false },
  { zh: '资产顾问', en: 'Property Advisors', app: 'Apps', level: 3, soon: false },
  { zh: '资产线索', en: 'Property Leads', app: 'Apps', level: 3, soon: false },
  { zh: '看房安排', en: 'Tour Schedule', app: 'Apps', level: 3, soon: false },
  { zh: '商城客户端', en: 'Store Client', app: 'Apps', level: 2, soon: false },
  { zh: '商城商品', en: 'Store Products', app: 'Apps', level: 3, soon: false },
  { zh: '商城订单', en: 'Store Orders', app: 'Apps', level: 3, soon: false },
  { zh: '项目计划', en: 'Project Planning', app: 'Apps', level: 2, soon: false },
  { zh: '商城管理端', en: 'Store Admin', app: 'Apps', level: 2, soon: false },
  { zh: '商城服务端', en: 'Store Services', app: 'Apps', level: 2, soon: false },
  { zh: 'AI 提示词', en: 'AI Prompt', app: 'Apps', level: 2, soon: false },
  { zh: '发票生成器', en: 'Invoice Generator', app: 'Apps', level: 2, soon: false },
];

const menuLabels = {
  en: {
    dashboards: 'Dashboards',
    dashboard: 'Operations Dashboard',
    public_profile: 'Public Profile',
    public_profile_overview: 'Overview',
    public_profile_projects: 'Projects',
    public_profile_projects_2_columns: '2 Columns',
    public_profile_projects_3_columns: '3 Columns',
    public_profile_activity: 'Activity',
    public_profile_teams: 'Teams',
    public_profile_variants: 'Profile Variants',
    public_profile_default: 'Default Profile',
    public_profile_company: 'Company Profile',
    public_profile_gamer: 'Gamer Profile',
    account: 'Account',
    account_home: 'Account Home',
    account_get_started: 'Get Started',
    account_user_profile: 'User Profile',
    account_company_profile: 'Company Profile',
    account_settings: 'Settings',
    account_settings_profile: 'Account Settings',
    account_settings_plain: 'Settings - Plain',
    account_settings_sidebar: 'Settings - Sidebar',
    account_settings_enterprise: 'Settings - Enterprise',
    account_appearance: 'Appearance',
    account_notifications: 'Notifications',
    account_integrations: 'Integrations',
    account_api_keys: 'API Keys',
    account_members: 'Members',
    account_members_starter: 'Members Starter',
    account_team_members: 'Team Members',
    account_import_members: 'Import Members',
    account_security: 'Security',
    account_security_log: 'Security Log',
    network: 'Network',
    network_user_cards: 'User Cards',
    network_user_cards_nft: 'NFT Cards',
    network_user_table: 'User Table',
    network_team_crew: 'Team Crew',
    auth_security: 'Auth & Security',
    auth_flow: 'Authentication Flow',
    auth_login: 'Sign In',
    auth_register: 'Sign Up',
    auth_forgot_password: 'Forgot Password',
    auth_update_password: 'Reset Password',
    auth_2fa: 'Two-Factor Auth',
    error_pages: 'Error Pages',
    error_404: 'Error 404',
    error_500: 'Error 500',
    apps: 'Apps',
    app_inventory: 'Inventory',
    app_inventory_dashboard: 'Inventory Dashboard',
    app_inventory_catalog: 'Catalog',
    app_inventory_customer: 'Customer',
    app_inventory_settings: 'Inventory Settings',
    products: 'Products',
    skus: 'SKU Management',
    categories: 'Categories',
    suppliers: 'Suppliers',
    warehouses: 'Warehouses',
    app_operations: 'Operations',
    stock_movements: 'Stock Movements',
    stock_transfers: 'Stock Transfers',
    cycle_counts: 'Cycle Counts',
    inventory_adjustments: 'Inventory Adjustments',
    reorder_rules: 'Reorder Rules',
    purchase_orders: 'Purchase Orders',
    sales_orders: 'Sales Orders',
    app_organization: 'User Management',
    app_user_management: 'User Management',
    users: 'Users',
    roles: 'Roles',
    permissions: 'Permissions',
    user_accounts: 'User Accounts',
    user_logs: 'Logs',
    user_settings: 'User Policies',
    app_planning: 'Planning',
    app_todo_lists: 'Todo Lists',
    app_todo_today: 'Today',
    app_todo_upcoming: 'Upcoming',
    app_todo_priority: 'Priority',
    app_todo_completed: 'Completed',
    app_todo_tags: 'Tags',
    calendar_events: 'Calendar',
    todos: 'Todo',
    app_ai: 'AI Assistant',
    app_ai_new_chat: 'New Chat',
    app_ai_templates: 'Templates',
    app_ai_settings: 'AI Settings',
    ai_conversations: 'AI Chat',
    app_communications: 'Notifications & Mail',
    notifications: 'Notification Center',
    app_mail: 'Mail',
    app_mail_direct_messages: 'Direct Messages',
    app_mail_support: 'Support',
    app_mail_settings: 'Mail Settings',
    app_mail_feedback: 'Feedback',
    app_mail_categories: 'Categories',
    mail_inbox: 'Inbox',
    mail_draft: 'Drafts',
    mail_sent: 'Sent',
    mail_archive: 'Archive',
    mail_snoozed: 'Snoozed',
    mail_spam: 'Spam',
    mail_trash: 'Trash',
    app_crm: 'CRM',
    app_crm_dashboard: 'CRM Dashboard',
    app_crm_tasks: 'Tasks',
    app_crm_notes: 'Notes',
    app_crm_companies: 'Companies',
    app_crm_reports: 'Reports',
    crm_accounts: 'Customer Accounts',
    crm_contacts: 'Customer Contacts',
    crm_deals: 'Revenue Opportunities',
    crm_activities: 'Customer Activities',
    app_property: 'Real Estate',
    app_property_buy: 'Buy',
    app_property_rent: 'Rent',
    app_property_sell: 'Sell',
    app_property_commercial: 'Commercial',
    app_property_saved: 'Saved',
    app_property_map_view: 'Map View',
    app_property_filters: 'Filters',
    properties: 'Property Portfolio',
    property_agents: 'Property Advisors',
    property_leads: 'Property Leads',
    property_showings: 'Tour Schedule',
    app_store: 'Store Client',
    store_client_products: 'Store Products',
    store_client_orders: 'Store Orders',
    app_project_planning: 'Project Planning',
    app_store_admin: 'Store Admin',
    app_store_services: 'Store Services',
    app_ai_prompt: 'AI Prompt',
    app_invoice_generator: 'Invoice Generator',
    account_billing: 'Billing',
    billing_plans: 'Plans',
    billing_invoices: 'Billing History',
    billing_subscriptions: 'Subscriptions',
    account_security_devices: 'Devices',
    account_security_sessions: 'Sessions',
    account_security_ips: 'Allowed IPs',
    account_referrals: 'Invite a Friend',
  },
  'zh-CN': {
    dashboards: '仪表盘',
    dashboard: '运营首页',
    public_profile: '个人资料',
    public_profile_overview: '资料概览',
    public_profile_projects: '项目',
    public_profile_projects_2_columns: '两栏项目',
    public_profile_projects_3_columns: '三栏项目',
    public_profile_activity: '活动',
    public_profile_teams: '团队',
    public_profile_variants: '资料变体',
    public_profile_default: '默认资料',
    public_profile_company: '企业资料',
    public_profile_gamer: '玩家资料',
    account: '我的账户',
    account_home: '账户首页',
    account_get_started: '开始使用',
    account_user_profile: '用户资料',
    account_company_profile: '公司资料',
    account_settings: '账户设置',
    account_settings_profile: '账户设置',
    account_settings_plain: '纯净设置',
    account_settings_sidebar: '侧边栏设置',
    account_settings_enterprise: '企业设置',
    account_appearance: '外观',
    account_notifications: '通知设置',
    account_integrations: '集成',
    account_api_keys: 'API 密钥',
    account_members: '成员',
    account_members_starter: '成员入门',
    account_team_members: '团队成员',
    account_import_members: '导入成员',
    account_security: '安全',
    account_security_log: '安全日志',
    network: '团队网络',
    network_user_cards: '用户卡片',
    network_user_cards_nft: 'NFT 卡片',
    network_user_table: '用户表格',
    network_team_crew: '团队成员表',
    auth_security: '系统页面',
    auth_flow: '登录流程',
    auth_login: '登录页',
    auth_register: '注册页',
    auth_forgot_password: '找回密码',
    auth_update_password: '重置密码',
    auth_2fa: '两步验证',
    error_pages: '错误页面',
    error_404: '404 页面',
    error_500: '500 页面',
    apps: '应用',
    app_inventory: '库存中心',
    app_inventory_dashboard: '库存驾驶舱',
    app_inventory_catalog: '目录资料',
    app_inventory_customer: '客户',
    app_inventory_settings: '库存设置',
    products: '商品档案',
    skus: 'SKU 管理',
    categories: '品类管理',
    suppliers: '供应商',
    warehouses: '仓库',
    app_operations: '运营作业',
    stock_movements: '库存流水',
    stock_transfers: '库存调拨',
    cycle_counts: '循环盘点',
    inventory_adjustments: '库存调整',
    reorder_rules: '补货规则',
    purchase_orders: '采购订单',
    sales_orders: '销售订单',
    app_organization: '用户管理',
    app_user_management: '用户管理',
    users: '用户',
    roles: '角色',
    permissions: '权限',
    user_accounts: '用户账户',
    user_logs: '日志',
    user_settings: '用户策略',
    app_planning: '计划日程',
    app_todo_lists: '待办清单',
    app_todo_today: '今日',
    app_todo_upcoming: '即将到来',
    app_todo_priority: '优先级',
    app_todo_completed: '已完成',
    app_todo_tags: '标签',
    calendar_events: '日历',
    todos: '待办事项',
    app_ai: '智能助手',
    app_ai_new_chat: '新建对话',
    app_ai_templates: '模板',
    app_ai_settings: 'AI 设置',
    ai_conversations: 'AI 对话',
    app_communications: '消息通知',
    notifications: '通知中心',
    app_mail: '邮件',
    app_mail_direct_messages: '直接消息',
    app_mail_support: '支持',
    app_mail_settings: '邮件设置',
    app_mail_feedback: '反馈',
    app_mail_categories: '分类',
    mail_inbox: '收件箱',
    mail_draft: '草稿箱',
    mail_sent: '已发送',
    mail_archive: '归档',
    mail_snoozed: '稍后提醒',
    mail_spam: '垃圾邮件',
    mail_trash: '废纸篓',
    app_crm: '客户经营',
    app_crm_dashboard: 'CRM 仪表盘',
    app_crm_tasks: '任务',
    app_crm_notes: '笔记',
    app_crm_companies: '公司',
    app_crm_reports: '报表',
    crm_accounts: '客户账户',
    crm_contacts: '客户联系人',
    crm_deals: '收入机会',
    crm_activities: '客户活动',
    app_property: '资产运营',
    app_property_buy: '购买',
    app_property_rent: '租赁',
    app_property_sell: '出售',
    app_property_commercial: '商业',
    app_property_saved: '已收藏',
    app_property_map_view: '地图视图',
    app_property_filters: '筛选器',
    properties: '资产组合',
    property_agents: '资产顾问',
    property_leads: '资产线索',
    property_showings: '看房安排',
    app_store: '商城客户端',
    store_client_products: '商城商品',
    store_client_orders: '商城订单',
    app_project_planning: '项目计划',
    app_store_admin: '商城管理端',
    app_store_services: '商城服务端',
    app_ai_prompt: 'AI 提示词',
    app_invoice_generator: '发票生成器',
    account_billing: '账单',
    billing_plans: '套餐方案',
    billing_invoices: '账单历史',
    billing_subscriptions: '订阅',
    account_security_devices: '设备管理',
    account_security_sessions: '当前会话',
    account_security_ips: '允许的 IP',
    account_referrals: '邀请好友',
  },
} satisfies Record<LocaleCode, Record<string, string>>;

type MenuKey = keyof typeof menuLabels.en;

function item(name: MenuKey, icon: string, href?: string, children?: MenuNode[], meta?: MenuNode['meta']): MenuNode {
  return { name, icon, href, children, meta };
}

function localize(items: MenuNode[], locale: string): MenuItem[] {
  const resolvedLocale: LocaleCode = locale === 'zh-CN' ? 'zh-CN' : 'en';
  return items.map((menuItem) => ({
    ...menuItem,
    label: menuLabels[resolvedLocale][menuItem.name],
    children: menuItem.children ? localize(menuItem.children, locale) : undefined,
  }));
}

export const exampleMenu: MenuNode[] = [
  item('dashboards', 'dashboard', undefined, [
    item('dashboard', 'dashboard', '/'),
  ]),
  item('public_profile', 'users', undefined, [
    item('public_profile_overview', 'home', '/public-profile'),
    item('public_profile_projects', 'folder', undefined, [
      item('public_profile_projects_2_columns', 'layout', '/public-profile/projects/2-columns'),
      item('public_profile_projects_3_columns', 'layout', '/public-profile/projects/3-columns'),
    ]),
    item('public_profile_activity', 'trending-up', '/public-profile/activity'),
    item('public_profile_teams', 'users', '/public-profile/teams'),
    item('public_profile_variants', 'images', undefined, [
      item('public_profile_default', 'users', '/public-profile/profiles/default'),
      item('public_profile_company', 'building', '/public-profile/profiles/company'),
      item('public_profile_gamer', 'sparkles', '/public-profile/profiles/gamer'),
    ]),
  ]),
  item('account', 'settings', undefined, [
    item('account_home', 'home', undefined, [
      item('account_get_started', 'sparkles', '/account/home/get-started'),
      item('account_user_profile', 'users', '/account/home/user-profile'),
      item('account_company_profile', 'building', '/account/home/company-profile'),
    ]),
    item('account_settings', 'settings', undefined, [
      item('account_settings_profile', 'settings', '/settings/account'),
      item('account_settings_plain', 'layout', '/account/home/settings-plain'),
      item('account_settings_sidebar', 'layout', '/account/home/settings-sidebar'),
      item('account_settings_enterprise', 'briefcase', '/account/home/settings-enterprise'),
      item('account_appearance', 'palette', '/account/appearance'),
      item('account_notifications', 'bell', '/account/notifications'),
      item('account_integrations', 'wrench', '/account/integrations'),
      item('account_api_keys', 'key-round', '/account/api-keys'),
    ]),
    item('account_billing', 'credit-card', undefined, [
      item('billing_plans', 'credit-card', '/billing_plans'),
      item('billing_invoices', 'file', '/billing_invoices'),
      item('billing_subscriptions', 'repeat', '/billing_subscriptions'),
    ]),
    item('account_members', 'users', undefined, [
      item('account_members_starter', 'sparkles', '/account/members/members-starter'),
      item('account_team_members', 'users', '/account/members/team-members'),
      item('account_import_members', 'download', '/account/members/import-members'),
    ]),
    item('account_security', 'shield', undefined, [
      item('account_security_log', 'book-open', '/account/security/security-log'),
      item('account_security_sessions', 'monitor', '/security_sessions'),
      item('account_security_devices', 'smartphone', '/security_devices'),
      item('account_security_ips', 'shield', '/security_allowed_ips'),
    ]),
    item('account_referrals', 'user-plus', '/referral_invites'),
  ]),
  item('network', 'briefcase', undefined, [
    item('network_user_cards', 'images', undefined, [
      item('network_user_cards_nft', 'images', '/network/user-cards/nft'),
    ]),
    item('network_user_table', 'users', undefined, [
      item('network_team_crew', 'users', '/network/user-table/team-crew'),
    ]),
  ]),
  item('auth_security', 'shield', undefined, [
    item('auth_flow', 'key-round', undefined, [
      item('auth_login', 'key', '/login'),
      item('auth_register', 'users', '/register'),
      item('auth_forgot_password', 'mail', '/forgot-password'),
      item('auth_update_password', 'key-round', '/update-password'),
    ]),
    item('auth_2fa', 'key', '/authentication/branded/2fa'),
    item('error_pages', 'alert-triangle', undefined, [
      item('error_404', 'alert-triangle', '/404'),
      item('error_500', 'alert-triangle', '/500'),
    ]),
  ]),
  item('apps', 'folder', undefined, [
    item('app_inventory', 'shopping-bag', undefined, [
      item('app_inventory_dashboard', 'dashboard', '/inventory-dashboard'),
      item('app_inventory_catalog', 'list-todo', undefined, [
        item('products', 'shopping-bag', '/products'),
        item('skus', 'tag', '/skus'),
        item('categories', 'layout', '/categories'),
      ]),
      item('suppliers', 'users', '/suppliers'),
      item('warehouses', 'home', '/warehouses'),
      item('app_inventory_customer', 'users', '/sales_orders?view=customers'),
      item('app_inventory_settings', 'settings', '/reorder_rules?view=settings'),
    ]),
    item('app_operations', 'list-todo', undefined, [
      item('stock_movements', 'trending-up', '/stock_movements'),
      item('stock_transfers', 'repeat', '/stock_transfers'),
      item('cycle_counts', 'clipboard-check', '/cycle_counts'),
      item('inventory_adjustments', 'sliders-horizontal', '/inventory_adjustments'),
      item('reorder_rules', 'alert-triangle', '/reorder_rules'),
      item('purchase_orders', 'download', '/purchase_orders'),
      item('sales_orders', 'credit-card', '/sales_orders'),
    ]),
    item('app_organization', 'users', undefined, [
      item('users', 'users', '/users'),
      item('roles', 'shield', '/roles?sort=name&order=asc'),
      item('permissions', 'key-round', '/permissions'),
      item('user_accounts', 'settings', '/user_accounts'),
      item('user_logs', 'book-open', '/user_logs'),
      item('user_settings', 'sliders-horizontal', '/user_settings'),
    ]),
    item('app_planning', 'calendar', undefined, [
      item('calendar_events', 'calendar', '/calendar_events'),
      item('app_todo_lists', 'list-todo', undefined, [
        item('todos', 'list-todo', '/todos'),
        item('app_todo_today', 'clock', '/todos?view=today'),
        item('app_todo_upcoming', 'calendar', '/todos?view=upcoming'),
        item('app_todo_priority', 'alert-triangle', '/todos?view=priority'),
        item('app_todo_completed', 'clipboard-check', '/todos?view=completed'),
        item('app_todo_tags', 'tag', '/todos?view=tags'),
      ]),
    ]),
    item('app_ai', 'bot', undefined, [
      item('app_ai_new_chat', 'sparkles', '/ai_conversations?view=new'),
      item('ai_conversations', 'bot', '/ai_conversations'),
      item('app_ai_templates', 'layout', '/ai_conversations?view=templates'),
      item('app_ai_settings', 'settings', '/user_settings?view=ai'),
    ]),
    item('app_communications', 'bell', undefined, [
      item('notifications', 'bell', '/notifications'),
      item('app_mail', 'mail', undefined, [
        item('mail_inbox', 'mail', '/mail_inbox'),
        item('mail_draft', 'file', '/mail_draft'),
        item('mail_sent', 'send', '/mail_sent'),
        item('mail_archive', 'book-open', '/mail_archive'),
        item('app_mail_settings', 'settings', '/user_settings?view=mail'),
      ]),
    ]),
    item('app_crm', 'briefcase', undefined, [
      item('app_crm_dashboard', 'dashboard', '/crm_accounts?view=dashboard'),
      item('crm_accounts', 'briefcase', '/crm_accounts'),
      item('crm_contacts', 'users', '/crm_contacts'),
      item('crm_deals', 'trending-up', '/crm_deals'),
      item('crm_activities', 'calendar', '/crm_activities'),
      item('app_crm_reports', 'trending-up', '/crm_deals?view=reports'),
    ]),
    item('app_property', 'building', undefined, [
      item('app_property_map_view', 'map', '/properties?view=map'),
      item('properties', 'home', '/properties'),
      item('property_agents', 'users', '/property_agents'),
      item('property_leads', 'trending-up', '/property_leads'),
      item('property_showings', 'calendar', '/property_showings'),
    ]),
    item('app_store', 'shopping-bag', undefined, [
      item('store_client_products', 'shopping-bag', '/store_client_products'),
      item('store_client_orders', 'credit-card', '/store_client_orders'),
    ]),
    item('app_project_planning', 'calendar', '/project_planning'),
    item('app_store_admin', 'settings', '/store_admin'),
    item('app_store_services', 'wrench', '/store_services'),
    item('app_ai_prompt', 'sparkles', '/ai_prompt'),
    item('app_invoice_generator', 'file', '/invoice_generator'),
  ]),
];

export function registerMenuTranslations(locale?: string): void {
  const locales: LocaleCode[] = locale === 'zh-CN' || locale === 'en' ? [locale] : ['en', 'zh-CN'];
  for (const currentLocale of locales) {
    addTranslations(
      currentLocale,
      Object.fromEntries(Object.entries(menuLabels[currentLocale]).map(([key, value]) => [`menu.${key}`, value])),
    );
  }
}

export function registerExampleMenuTranslations(locale?: string): void {
  registerMenuTranslations(locale);
}

export function createExampleMenu(locale: string): MenuItem[] {
  return localize(exampleMenu, locale);
}
