import type { ResourceDefinition } from '@svadmin/core';

const inventoryGroup = 'Inventory';
const operationsGroup = 'Operations';
const peopleGroup = 'User Management';
const planningGroup = 'Planning';
const intelligenceGroup = 'Intelligence';
const communicationGroup = 'Notifications';

export const resources: ResourceDefinition[] = [
  {
    name: 'products',
    label: 'Products',
    icon: 'folder',
    group: inventoryGroup,
    menuOrder: 10,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'sku', label: 'SKU', type: 'text', required: true, searchable: true, width: '140px' },
      { key: 'categoryId', label: 'Category', type: 'relation', resource: 'categories', optionLabel: 'name', optionValue: 'id' },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id' },
      { key: 'price', label: 'Price', type: 'number', required: true, width: '110px' },
      { key: 'stock', label: 'Stock', type: 'number', required: true, width: '100px' },
      { key: 'minStock', label: 'Min Stock', type: 'number', required: true, width: '110px' },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'skus',
    label: 'SKUs',
    icon: 'folder',
    group: inventoryGroup,
    menuOrder: 20,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'sku', label: 'SKU', type: 'text', required: true, searchable: true, width: '140px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'barcode', label: 'Barcode', type: 'text', searchable: true },
      { key: 'variant', label: 'Variant', type: 'text', searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Paused', value: 'paused' },
          { label: 'Retired', value: 'retired' },
        ],
      },
    ],
    defaultSort: { field: 'sku', order: 'asc' },
  },
  {
    name: 'categories',
    label: 'Categories',
    icon: 'folder',
    group: inventoryGroup,
    menuOrder: 30,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'code', label: 'Code', type: 'text', required: true, width: '100px' },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'suppliers',
    label: 'Suppliers',
    icon: 'users',
    group: inventoryGroup,
    menuOrder: 40,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'contactName', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'phone' },
      { key: 'address', label: 'Address', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'warehouses',
    label: 'Warehouses',
    icon: 'home',
    group: inventoryGroup,
    menuOrder: 50,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'code', label: 'Code', type: 'text', required: true, width: '120px' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'capacity', label: 'Capacity', type: 'number', width: '110px' },
      { key: 'utilization', label: 'Utilization %', type: 'number', width: '130px' },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'stock_movements',
    label: 'Stock Movements',
    icon: 'trending-up',
    group: operationsGroup,
    menuOrder: 60,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Inbound', value: 'in' },
          { label: 'Outbound', value: 'out' },
          { label: 'Adjustment', value: 'adjustment' },
        ],
      },
      { key: 'note', label: 'Note', type: 'text' },
      { key: 'date', label: 'Date', type: 'date', required: true, width: '130px' },
    ],
    defaultSort: { field: 'date', order: 'desc' },
  },
  {
    name: 'purchase_orders',
    label: 'Purchase Orders',
    icon: 'download',
    group: operationsGroup,
    menuOrder: 100,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Ordered', value: 'ordered' },
          { label: 'Received', value: 'received' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
      { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
      { key: 'deliveryDate', label: 'Delivery Date', type: 'date' },
    ],
    defaultSort: { field: 'orderDate', order: 'desc' },
  },
  {
    name: 'sales_orders',
    label: 'Sales Orders',
    icon: 'credit-card',
    group: operationsGroup,
    menuOrder: 110,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
      { key: 'customerName', label: 'Customer Name', type: 'text', required: true, searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Pending', value: 'pending' },
          { label: 'Processing', value: 'processing' },
          { label: 'Shipped', value: 'shipped' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
      { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
      { key: 'shippingDate', label: 'Shipping Date', type: 'date' },
    ],
    defaultSort: { field: 'orderDate', order: 'desc' },
  },
  {
    name: 'todos',
    label: 'Todo',
    icon: 'list-todo',
    group: operationsGroup,
    menuOrder: 120,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      { key: 'assigneeId', label: 'Assignee', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        options: [
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Open', value: 'open' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Blocked', value: 'blocked' },
          { label: 'Done', value: 'done' },
        ],
      },
      { key: 'completed', label: 'Done', type: 'boolean', width: '90px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'dueDate', order: 'asc' },
  },
  {
    name: 'stock_transfers',
    label: 'Stock Transfers',
    icon: 'repeat',
    group: operationsGroup,
    menuOrder: 70,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'transferNumber', label: 'Transfer Number', type: 'text', required: true, searchable: true },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'fromWarehouseId', label: 'From Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'toWarehouseId', label: 'To Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Approved', value: 'approved' },
          { label: 'In Transit', value: 'in_transit' },
          { label: 'Received', value: 'received' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
      { key: 'expectedDate', label: 'Expected Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'requestedDate', order: 'desc' },
  },
  {
    name: 'cycle_counts',
    label: 'Cycle Counts',
    icon: 'clipboard-check',
    group: operationsGroup,
    menuOrder: 80,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'countNumber', label: 'Count Number', type: 'text', required: true, searchable: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'scheduledDate', label: 'Scheduled Date', type: 'date', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Reconciled', value: 'reconciled' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'scope', label: 'Scope', type: 'text', searchable: true },
      { key: 'expectedItems', label: 'Expected Items', type: 'number', width: '130px' },
      { key: 'countedItems', label: 'Counted Items', type: 'number', width: '130px' },
      { key: 'varianceItems', label: 'Variance Items', type: 'number', width: '130px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'scheduledDate', order: 'asc' },
  },
  {
    name: 'inventory_adjustments',
    label: 'Inventory Adjustments',
    icon: 'sliders-horizontal',
    group: operationsGroup,
    menuOrder: 90,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'adjustmentNumber', label: 'Adjustment Number', type: 'text', required: true, searchable: true },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantityChange', label: 'Quantity Change', type: 'number', required: true, width: '140px' },
      {
        key: 'reason',
        label: 'Reason',
        type: 'select',
        required: true,
        options: [
          { label: 'Damage', value: 'damage' },
          { label: 'Cycle Count Variance', value: 'cycle_count_variance' },
          { label: 'Return Correction', value: 'return_correction' },
          { label: 'System Correction', value: 'system_correction' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Pending Approval', value: 'pending_approval' },
          { label: 'Approved', value: 'approved' },
          { label: 'Rejected', value: 'rejected' },
        ],
      },
      { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'approvedById', label: 'Approved By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'requestedDate', order: 'desc' },
  },
  {
    name: 'reorder_rules',
    label: 'Reorder Rules',
    icon: 'alert-triangle',
    group: operationsGroup,
    menuOrder: 95,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'minStock', label: 'Min Stock', type: 'number', required: true, width: '110px' },
      { key: 'targetStock', label: 'Target Stock', type: 'number', required: true, width: '120px' },
      { key: 'reorderQuantity', label: 'Reorder Qty', type: 'number', required: true, width: '120px' },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id' },
      { key: 'leadTimeDays', label: 'Lead Time Days', type: 'number', width: '140px' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Review', value: 'review' },
          { label: 'Paused', value: 'paused' },
        ],
      },
      { key: 'lastReviewedAt', label: 'Last Reviewed', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'lastReviewedAt', order: 'desc' },
  },
  {
    name: 'users',
    label: 'Users',
    icon: 'users',
    group: peopleGroup,
    menuOrder: 100,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'email', label: 'Email', type: 'email', required: true, searchable: true },
      { key: 'roleId', label: 'Role', type: 'relation', resource: 'roles', optionLabel: 'name', optionValue: 'id', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Invited', value: 'invited' },
          { label: 'Suspended', value: 'suspended' },
        ],
      },
      { key: 'department', label: 'Department', type: 'text', searchable: true },
      { key: 'lastActiveAt', label: 'Last Active', type: 'date' },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'roles',
    label: 'Roles',
    icon: 'shield',
    group: peopleGroup,
    menuOrder: 110,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'scope', label: 'Scope', type: 'text', required: true, searchable: true },
      {
        key: 'level',
        label: 'Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Owner', value: 'owner' },
          { label: 'Manager', value: 'manager' },
          { label: 'Operator', value: 'operator' },
          { label: 'Viewer', value: 'viewer' },
        ],
      },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'calendar_events',
    label: 'Calendar',
    icon: 'calendar',
    group: planningGroup,
    menuOrder: 120,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Purchase', value: 'purchase' },
          { label: 'Cycle Count', value: 'cycle_count' },
          { label: 'Receiving', value: 'receiving' },
          { label: 'Review', value: 'review' },
        ],
      },
      { key: 'startDate', label: 'Start Date', type: 'date', required: true },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Done', value: 'done' },
        ],
      },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'startDate', order: 'asc' },
  },
  {
    name: 'ai_conversations',
    label: 'AI Chat',
    icon: 'bot',
    group: intelligenceGroup,
    menuOrder: 130,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'intent',
        label: 'Intent',
        type: 'select',
        required: true,
        options: [
          { label: 'Replenishment', value: 'replenishment' },
          { label: 'Forecast', value: 'forecast' },
          { label: 'Exception Review', value: 'exception_review' },
          { label: 'Policy Help', value: 'policy_help' },
        ],
      },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Open', value: 'open' },
          { label: 'Waiting', value: 'waiting' },
          { label: 'Resolved', value: 'resolved' },
        ],
      },
      { key: 'lastMessage', label: 'Last Message', type: 'textarea' },
      { key: 'updatedAt', label: 'Updated', type: 'date' },
    ],
    defaultSort: { field: 'updatedAt', order: 'desc' },
  },
  {
    name: 'notifications',
    label: 'Notification Center',
    icon: 'bell',
    group: communicationGroup,
    menuOrder: 140,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'channel',
        label: 'Channel',
        type: 'select',
        required: true,
        options: [
          { label: 'System', value: 'system' },
          { label: 'Inventory', value: 'inventory' },
          { label: 'Order', value: 'order' },
          { label: 'Security', value: 'security' },
        ],
      },
      {
        key: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Warning', value: 'warning' },
          { label: 'Critical', value: 'critical' },
        ],
      },
      { key: 'recipientId', label: 'Recipient', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'read', label: 'Read', type: 'boolean', width: '90px' },
      { key: 'createdAt', label: 'Created', type: 'date', required: true },
      { key: 'body', label: 'Body', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'createdAt', order: 'desc' },
  },
];
