import type { ResourceDefinition } from '@svadmin/core';

const inventoryGroup = 'Inventory';
const operationsGroup = 'Operations';
const peopleGroup = 'User Management';
const planningGroup = 'Planning';
const intelligenceGroup = 'Intelligence';
const communicationGroup = 'Notifications';
const customerGroup = 'Customer Operations';
const propertyGroup = 'Property Operations';

export const resources: ResourceDefinition[] = [
  {
    name: 'products',
    label: 'Products',
    icon: 'package',
    group: inventoryGroup,
    menuOrder: 10,
    meta: { badge: '4' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'sku', label: 'SKU', type: 'text', required: true, searchable: true, width: '140px' },
      { key: 'categoryId', label: 'Category', type: 'relation', resource: 'categories', optionLabel: 'name', optionValue: 'id' },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id' },
      { key: 'price', label: 'Price', type: 'number', required: true, width: '110px' },
      { key: 'stock', label: 'Stock', type: 'number', required: true, width: '100px' },
      { key: 'minStock', label: 'Min Stock', type: 'number', required: true, width: '110px' },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'skus',
    label: 'SKUs',
    icon: 'barcode',
    group: inventoryGroup,
    menuOrder: 20,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'sku', label: 'SKU', type: 'text', required: true, searchable: true, width: '140px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'barcode', label: 'Barcode', type: 'text', searchable: true },
      { key: 'variant', label: 'Variant', type: 'text', searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Paused', value: 'paused' },
          { label: 'Retired', value: 'retired' },
        ],
      },
    ],
    defaultSort: { field: 'sku', order: 'asc' },
  },
  {
    name: 'categories',
    label: 'Categories',
    icon: 'folder-tree',
    group: inventoryGroup,
    menuOrder: 30,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'code', label: 'Code', type: 'text', required: true, width: '100px' },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'suppliers',
    label: 'Suppliers',
    icon: 'building-2',
    group: inventoryGroup,
    menuOrder: 40,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'contactName', label: 'Contact Name', type: 'text' },
      { key: 'email', label: 'Email', type: 'email' },
      { key: 'phone', label: 'Phone', type: 'phone' },
      { key: 'address', label: 'Address', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'warehouses',
    label: 'Warehouses',
    icon: 'warehouse',
    group: inventoryGroup,
    menuOrder: 50,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'code', label: 'Code', type: 'text', required: true, width: '120px' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'capacity', label: 'Capacity', type: 'number', width: '110px' },
      { key: 'utilization', label: 'Utilization %', type: 'number', width: '130px' },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'stock_movements',
    label: 'Stock Movements',
    icon: 'trending-up',
    group: operationsGroup,
    menuOrder: 60,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Inbound', value: 'in' },
          { label: 'Outbound', value: 'out' },
          { label: 'Adjustment', value: 'adjustment' },
        ],
      },
      { key: 'note', label: 'Note', type: 'text' },
      { key: 'date', label: 'Date', type: 'date', required: true, width: '130px' },
    ],
    defaultSort: { field: 'date', order: 'desc' },
  },
  {
    name: 'purchase_orders',
    label: 'Purchase Orders',
    icon: 'download',
    group: operationsGroup,
    menuOrder: 100,
    meta: { badge: '3' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Ordered', value: 'ordered' },
          { label: 'Received', value: 'received' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
      { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
      { key: 'deliveryDate', label: 'Delivery Date', type: 'date' },
    ],
    defaultSort: { field: 'orderDate', order: 'desc' },
  },
  {
    name: 'sales_orders',
    label: 'Sales Orders',
    icon: 'credit-card',
    group: operationsGroup,
    menuOrder: 110,
    meta: { badge: '2' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'orderNumber', label: 'Order Number', type: 'text', required: true, searchable: true },
      { key: 'customerName', label: 'Customer Name', type: 'text', required: true, searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Pending', value: 'pending' },
          { label: 'Processing', value: 'processing' },
          { label: 'Shipped', value: 'shipped' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'totalAmount', label: 'Total Amount', type: 'number', required: true },
      { key: 'orderDate', label: 'Order Date', type: 'date', required: true },
      { key: 'shippingDate', label: 'Shipping Date', type: 'date' },
    ],
    defaultSort: { field: 'orderDate', order: 'desc' },
  },
  {
    name: 'todos',
    label: 'Todo',
    icon: 'list-todo',
    group: operationsGroup,
    menuOrder: 120,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      { key: 'assigneeId', label: 'Assignee', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        options: [
          { label: 'High', value: 'high' },
          { label: 'Medium', value: 'medium' },
          { label: 'Low', value: 'low' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Open', value: 'open' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Blocked', value: 'blocked' },
          { label: 'Done', value: 'done' },
        ],
      },
      { key: 'completed', label: 'Done', type: 'boolean', width: '90px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'dueDate', order: 'asc' },
  },
  {
    name: 'stock_transfers',
    label: 'Stock Transfers',
    icon: 'repeat',
    group: operationsGroup,
    menuOrder: 70,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'transferNumber', label: 'Transfer Number', type: 'text', required: true, searchable: true },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'fromWarehouseId', label: 'From Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'toWarehouseId', label: 'To Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantity', label: 'Quantity', type: 'number', required: true, width: '110px' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Approved', value: 'approved' },
          { label: 'In Transit', value: 'in_transit' },
          { label: 'Received', value: 'received' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
      { key: 'expectedDate', label: 'Expected Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'requestedDate', order: 'desc' },
  },
  {
    name: 'cycle_counts',
    label: 'Cycle Counts',
    icon: 'clipboard-check',
    group: operationsGroup,
    menuOrder: 80,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'countNumber', label: 'Count Number', type: 'text', required: true, searchable: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'scheduledDate', label: 'Scheduled Date', type: 'date', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Reconciled', value: 'reconciled' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'scope', label: 'Scope', type: 'text', searchable: true },
      { key: 'expectedItems', label: 'Expected Items', type: 'number', width: '130px' },
      { key: 'countedItems', label: 'Counted Items', type: 'number', width: '130px' },
      { key: 'varianceItems', label: 'Variance Items', type: 'number', width: '130px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'scheduledDate', order: 'asc' },
  },
  {
    name: 'inventory_adjustments',
    label: 'Inventory Adjustments',
    icon: 'sliders-horizontal',
    group: operationsGroup,
    menuOrder: 90,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'adjustmentNumber', label: 'Adjustment Number', type: 'text', required: true, searchable: true },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'quantityChange', label: 'Quantity Change', type: 'number', required: true, width: '140px' },
      {
        key: 'reason',
        label: 'Reason',
        type: 'select',
        required: true,
        options: [
          { label: 'Damage', value: 'damage' },
          { label: 'Cycle Count Variance', value: 'cycle_count_variance' },
          { label: 'Return Correction', value: 'return_correction' },
          { label: 'System Correction', value: 'system_correction' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Pending Approval', value: 'pending_approval' },
          { label: 'Approved', value: 'approved' },
          { label: 'Rejected', value: 'rejected' },
        ],
      },
      { key: 'requestedById', label: 'Requested By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'approvedById', label: 'Approved By', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'requestedDate', label: 'Requested Date', type: 'date', required: true },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'requestedDate', order: 'desc' },
  },
  {
    name: 'reorder_rules',
    label: 'Reorder Rules',
    icon: 'alert-triangle',
    group: operationsGroup,
    menuOrder: 95,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'productId', label: 'Product', type: 'relation', resource: 'products', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id', required: true },
      { key: 'minStock', label: 'Min Stock', type: 'number', required: true, width: '110px' },
      { key: 'targetStock', label: 'Target Stock', type: 'number', required: true, width: '120px' },
      { key: 'reorderQuantity', label: 'Reorder Qty', type: 'number', required: true, width: '120px' },
      { key: 'supplierId', label: 'Supplier', type: 'relation', resource: 'suppliers', optionLabel: 'name', optionValue: 'id' },
      { key: 'leadTimeDays', label: 'Lead Time Days', type: 'number', width: '140px' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Review', value: 'review' },
          { label: 'Paused', value: 'paused' },
        ],
      },
      { key: 'lastReviewedAt', label: 'Last Reviewed', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'lastReviewedAt', order: 'desc' },
  },
  {
    name: 'users',
    label: 'Users',
    icon: 'users',
    group: peopleGroup,
    menuOrder: 100,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'email', label: 'Email', type: 'email', required: true, searchable: true },
      { key: 'roleId', label: 'Role', type: 'relation', resource: 'roles', optionLabel: 'name', optionValue: 'id', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Invited', value: 'invited' },
          { label: 'Suspended', value: 'suspended' },
        ],
      },
      { key: 'department', label: 'Department', type: 'text', searchable: true },
      { key: 'lastActiveAt', label: 'Last Active', type: 'date' },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'roles',
    label: 'Roles',
    icon: 'shield',
    group: peopleGroup,
    menuOrder: 110,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'scope', label: 'Scope', type: 'text', required: true, searchable: true },
      {
        key: 'level',
        label: 'Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Owner', value: 'owner' },
          { label: 'Manager', value: 'manager' },
          { label: 'Operator', value: 'operator' },
          { label: 'Viewer', value: 'viewer' },
        ],
      },
      { key: 'description', label: 'Description', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'calendar_events',
    label: 'Calendar',
    icon: 'calendar',
    group: planningGroup,
    menuOrder: 120,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Purchase', value: 'purchase' },
          { label: 'Cycle Count', value: 'cycle_count' },
          { label: 'Receiving', value: 'receiving' },
          { label: 'Review', value: 'review' },
        ],
      },
      { key: 'startDate', label: 'Start Date', type: 'date', required: true },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'warehouseId', label: 'Warehouse', type: 'relation', resource: 'warehouses', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'In Progress', value: 'in_progress' },
          { label: 'Done', value: 'done' },
        ],
      },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'startDate', order: 'asc' },
  },
  {
    name: 'ai_conversations',
    label: 'AI Chat',
    icon: 'bot',
    group: intelligenceGroup,
    menuOrder: 130,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'intent',
        label: 'Intent',
        type: 'select',
        required: true,
        options: [
          { label: 'Replenishment', value: 'replenishment' },
          { label: 'Forecast', value: 'forecast' },
          { label: 'Exception Review', value: 'exception_review' },
          { label: 'Policy Help', value: 'policy_help' },
        ],
      },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        required: true,
        options: [
          { label: 'Open', value: 'open' },
          { label: 'Waiting', value: 'waiting' },
          { label: 'Resolved', value: 'resolved' },
        ],
      },
      { key: 'lastMessage', label: 'Last Message', type: 'textarea' },
      { key: 'updatedAt', label: 'Updated', type: 'date' },
    ],
    defaultSort: { field: 'updatedAt', order: 'desc' },
  },
  {
    name: 'notifications',
    label: 'Notification Center',
    icon: 'bell',
    group: communicationGroup,
    menuOrder: 140,
    meta: { badge: '3' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'title', label: 'Title', type: 'text', required: true, searchable: true },
      {
        key: 'channel',
        label: 'Channel',
        type: 'select',
        required: true,
        options: [
          { label: 'System', value: 'system' },
          { label: 'Inventory', value: 'inventory' },
          { label: 'Order', value: 'order' },
          { label: 'Security', value: 'security' },
        ],
      },
      {
        key: 'severity',
        label: 'Severity',
        type: 'select',
        required: true,
        options: [
          { label: 'Info', value: 'info' },
          { label: 'Warning', value: 'warning' },
          { label: 'Critical', value: 'critical' },
        ],
      },
      { key: 'recipientId', label: 'Recipient', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      { key: 'read', label: 'Read', type: 'boolean', width: '90px' },
      { key: 'createdAt', label: 'Created', type: 'date', required: true },
      { key: 'body', label: 'Body', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'createdAt', order: 'desc' },
  },
  {
    name: 'crm_accounts',
    label: 'Customer Accounts',
    icon: 'briefcase-business',
    group: customerGroup,
    menuOrder: 150,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'accountName', label: 'Account Name', type: 'text', required: true, searchable: true },
      {
        key: 'segment',
        label: 'Segment',
        type: 'select',
        required: true,
        options: [
          { label: 'Strategic', value: 'strategic' },
          { label: 'Growth', value: 'growth' },
          { label: 'Renewal', value: 'renewal' },
        ],
      },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'health',
        label: 'Health',
        type: 'select',
        required: true,
        options: [
          { label: 'Healthy', value: 'healthy' },
          { label: 'Watch', value: 'watch' },
          { label: 'At Risk', value: 'at_risk' },
        ],
      },
      { key: 'annualValue', label: 'Annual Value', type: 'number', width: '130px' },
      { key: 'nextReview', label: 'Next Review', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'accountName', order: 'asc' },
  },
  {
    name: 'crm_contacts',
    label: 'Customer Contacts',
    icon: 'user-round-check',
    group: customerGroup,
    menuOrder: 160,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'fullName', label: 'Full Name', type: 'text', required: true, searchable: true },
      { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
      { key: 'email', label: 'Email', type: 'email', searchable: true },
      { key: 'phone', label: 'Phone', type: 'phone' },
      { key: 'roleTitle', label: 'Role Title', type: 'text', searchable: true },
      {
        key: 'influence',
        label: 'Influence',
        type: 'select',
        options: [
          { label: 'Decision Maker', value: 'decision_maker' },
          { label: 'Evaluator', value: 'evaluator' },
          { label: 'Operator', value: 'operator' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'New', value: 'new' },
          { label: 'Paused', value: 'paused' },
        ],
      },
      { key: 'lastTouchDate', label: 'Last Touch', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'lastTouchDate', order: 'desc' },
  },
  {
    name: 'crm_deals',
    label: 'Revenue Opportunities',
    icon: 'handshake',
    group: customerGroup,
    menuOrder: 170,
    meta: { badge: '3' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'dealName', label: 'Opportunity Name', type: 'text', required: true, searchable: true },
      { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
      { key: 'contactId', label: 'Contact', type: 'relation', resource: 'crm_contacts', optionLabel: 'fullName', optionValue: 'id' },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'stage',
        label: 'Stage',
        type: 'select',
        required: true,
        options: [
          { label: 'Discovery', value: 'discovery' },
          { label: 'Proposal', value: 'proposal' },
          { label: 'Negotiation', value: 'negotiation' },
          { label: 'Won', value: 'won' },
          { label: 'Lost', value: 'lost' },
        ],
      },
      { key: 'amount', label: 'Amount', type: 'number', required: true, width: '120px' },
      { key: 'probability', label: 'Probability %', type: 'number', width: '130px' },
      { key: 'closeDate', label: 'Close Date', type: 'date' },
      { key: 'nextStep', label: 'Next Step', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'closeDate', order: 'asc' },
  },
  {
    name: 'crm_activities',
    label: 'Customer Activities',
    icon: 'calendar-check',
    group: customerGroup,
    menuOrder: 180,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'subject', label: 'Subject', type: 'text', required: true, searchable: true },
      { key: 'accountId', label: 'Account', type: 'relation', resource: 'crm_accounts', optionLabel: 'accountName', optionValue: 'id' },
      { key: 'contactId', label: 'Contact', type: 'relation', resource: 'crm_contacts', optionLabel: 'fullName', optionValue: 'id' },
      { key: 'dealId', label: 'Opportunity', type: 'relation', resource: 'crm_deals', optionLabel: 'dealName', optionValue: 'id' },
      { key: 'ownerId', label: 'Owner', type: 'relation', resource: 'users', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'Call', value: 'call' },
          { label: 'Demo', value: 'demo' },
          { label: 'Review', value: 'review' },
          { label: 'Email', value: 'email' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Planned', value: 'planned' },
          { label: 'Completed', value: 'completed' },
          { label: 'Follow Up', value: 'follow_up' },
        ],
      },
      { key: 'dueDate', label: 'Due Date', type: 'date' },
      { key: 'outcome', label: 'Outcome', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'dueDate', order: 'asc' },
  },
  {
    name: 'properties',
    label: 'Property Portfolio',
    icon: 'building-2',
    group: propertyGroup,
    menuOrder: 190,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'propertyName', label: 'Property Name', type: 'text', required: true, searchable: true },
      { key: 'market', label: 'Market', type: 'text', required: true, searchable: true },
      {
        key: 'assetType',
        label: 'Asset Type',
        type: 'select',
        required: true,
        options: [
          { label: 'Multifamily', value: 'multifamily' },
          { label: 'Office', value: 'office' },
          { label: 'Retail', value: 'retail' },
          { label: 'Industrial', value: 'industrial' },
        ],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Renovation', value: 'renovation' },
          { label: 'Listed', value: 'listed' },
          { label: 'Under Contract', value: 'under_contract' },
        ],
      },
      { key: 'managerId', label: 'Manager', type: 'relation', resource: 'property_agents', optionLabel: 'name', optionValue: 'id' },
      { key: 'units', label: 'Units', type: 'number', width: '90px' },
      { key: 'occupancy', label: 'Occupancy %', type: 'number', width: '130px' },
      { key: 'askingPrice', label: 'Asking Price', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'propertyName', order: 'asc' },
  },
  {
    name: 'property_agents',
    label: 'Property Advisors',
    icon: 'key-round',
    group: propertyGroup,
    menuOrder: 200,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'name', label: 'Name', type: 'text', required: true, searchable: true },
      { key: 'email', label: 'Email', type: 'email', searchable: true },
      { key: 'phone', label: 'Phone', type: 'phone' },
      { key: 'territory', label: 'Territory', type: 'text', searchable: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'On Leave', value: 'on_leave' },
          { label: 'Paused', value: 'paused' },
        ],
      },
      { key: 'capacityScore', label: 'Capacity Score', type: 'number', width: '140px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'name', order: 'asc' },
  },
  {
    name: 'property_leads',
    label: 'Property Leads',
    icon: 'map-pinned',
    group: propertyGroup,
    menuOrder: 210,
    meta: { badge: '4' },
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'leadName', label: 'Lead Name', type: 'text', required: true, searchable: true },
      { key: 'propertyId', label: 'Property', type: 'relation', resource: 'properties', optionLabel: 'propertyName', optionValue: 'id' },
      { key: 'agentId', label: 'Advisor', type: 'relation', resource: 'property_agents', optionLabel: 'name', optionValue: 'id' },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        options: [
          { label: 'Referral', value: 'referral' },
          { label: 'Portal', value: 'portal' },
          { label: 'Walk In', value: 'walk_in' },
          { label: 'Partner', value: 'partner' },
        ],
      },
      { key: 'budget', label: 'Budget', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'New', value: 'new' },
          { label: 'Qualified', value: 'qualified' },
          { label: 'Tour Scheduled', value: 'tour_scheduled' },
          { label: 'Offer', value: 'offer' },
          { label: 'Dormant', value: 'dormant' },
        ],
      },
      { key: 'targetMoveDate', label: 'Target Move Date', type: 'date' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'targetMoveDate', order: 'asc' },
  },
  {
    name: 'property_showings',
    label: 'Tour Schedule',
    icon: 'calendar-check',
    group: propertyGroup,
    menuOrder: 220,
    fields: [
      { key: 'id', label: 'ID', type: 'number', showInForm: false, width: '72px' },
      { key: 'showingNumber', label: 'Tour Number', type: 'text', required: true, searchable: true },
      { key: 'propertyId', label: 'Property', type: 'relation', resource: 'properties', optionLabel: 'propertyName', optionValue: 'id' },
      { key: 'leadId', label: 'Lead', type: 'relation', resource: 'property_leads', optionLabel: 'leadName', optionValue: 'id' },
      { key: 'agentId', label: 'Advisor', type: 'relation', resource: 'property_agents', optionLabel: 'name', optionValue: 'id' },
      { key: 'scheduledDate', label: 'Scheduled Date', type: 'date', required: true },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Scheduled', value: 'scheduled' },
          { label: 'Completed', value: 'completed' },
          { label: 'Rescheduled', value: 'rescheduled' },
          { label: 'Cancelled', value: 'cancelled' },
        ],
      },
      { key: 'feedbackScore', label: 'Feedback Score', type: 'number', width: '140px' },
      { key: 'notes', label: 'Notes', type: 'textarea', showInList: false },
    ],
    defaultSort: { field: 'scheduledDate', order: 'asc' },
  },
];

const zhGroupLabels: Record<string, string> = {
  Inventory: '库存中心',
  Operations: '运营作业',
  'User Management': '组织权限',
  Planning: '计划日程',
  Intelligence: '智能助手',
  Notifications: '消息通知',
  'Customer Operations': '客户经营',
  'Property Operations': '资产运营',
};

const zhResourceLabels: Record<string, string> = {
  Products: '商品档案',
  SKUs: 'SKU 管理',
  Categories: '品类管理',
  Suppliers: '供应商',
  Warehouses: '仓库',
  'Stock Movements': '库存流水',
  'Purchase Orders': '采购订单',
  'Sales Orders': '销售订单',
  Todo: '待办事项',
  'Stock Transfers': '库存调拨',
  'Cycle Counts': '循环盘点',
  'Inventory Adjustments': '库存调整',
  'Reorder Rules': '补货规则',
  Users: '用户',
  Roles: '角色',
  Calendar: '日程',
  'AI Chat': 'AI 对话',
  'Notification Center': '通知中心',
  'Customer Accounts': '客户账户',
  'Customer Contacts': '客户联系人',
  'Revenue Opportunities': '收入机会',
  'Customer Activities': '客户活动',
  'Property Portfolio': '资产组合',
  'Property Advisors': '资产顾问',
  'Property Leads': '资产线索',
  'Tour Schedule': '看房安排',
};

const zhFieldLabels: Record<string, string> = {
  ID: 'ID',
  Name: '名称',
  SKU: 'SKU',
  Category: '品类',
  Supplier: '供应商',
  Price: '价格',
  Stock: '库存',
  'Min Stock': '最低库存',
  Description: '描述',
  Barcode: '条码',
  Variant: '规格',
  Status: '状态',
  Code: '编码',
  'Contact Name': '联系人',
  Email: '邮箱',
  Phone: '电话',
  Address: '地址',
  Location: '位置',
  Capacity: '容量',
  'Utilization %': '利用率 %',
  Product: '商品',
  Warehouse: '仓库',
  Quantity: '数量',
  Type: '类型',
  Note: '备注',
  Date: '日期',
  'Order Number': '订单号',
  'Total Amount': '总金额',
  'Order Date': '下单日期',
  'Delivery Date': '交付日期',
  'Customer Name': '客户名称',
  'Shipping Date': '发货日期',
  Title: '标题',
  Assignee: '负责人',
  'Due Date': '截止日期',
  Priority: '优先级',
  Done: '完成',
  Notes: '备注',
  'Transfer Number': '调拨单号',
  'From Warehouse': '调出仓',
  'To Warehouse': '调入仓',
  'Requested By': '申请人',
  'Requested Date': '申请日期',
  'Expected Date': '预计日期',
  'Count Number': '盘点单号',
  Owner: '负责人',
  'Scheduled Date': '计划日期',
  Scope: '范围',
  'Expected Items': '应盘项',
  'Counted Items': '已盘项',
  'Variance Items': '差异项',
  'Adjustment Number': '调整单号',
  'Quantity Change': '调整数量',
  Reason: '原因',
  'Approved By': '审批人',
  'Target Stock': '目标库存',
  'Reorder Qty': '补货数量',
  'Lead Time Days': '提前期天数',
  'Last Reviewed': '上次复核',
  Role: '角色',
  Department: '部门',
  'Last Active': '最近活跃',
  Level: '等级',
  'Start Date': '开始日期',
  'End Date': '结束日期',
  Intent: '意图',
  'Last Message': '最后消息',
  Updated: '更新时间',
  Channel: '渠道',
  Severity: '严重性',
  Recipient: '接收人',
  Read: '已读',
  Created: '创建时间',
  Body: '内容',
  'Account Name': '账户名称',
  Segment: '分层',
  Health: '健康度',
  'Annual Value': '年度价值',
  'Next Review': '下次复盘',
  'Full Name': '姓名',
  Account: '账户',
  'Role Title': '角色头衔',
  Influence: '影响力',
  'Last Touch': '最近触达',
  'Opportunity Name': '机会名称',
  Contact: '联系人',
  Opportunity: '机会',
  Stage: '阶段',
  Amount: '金额',
  'Probability %': '概率 %',
  'Close Date': '预计成交日',
  'Next Step': '下一步',
  Subject: '主题',
  Outcome: '结果',
  'Property Name': '资产名称',
  Market: '市场',
  'Asset Type': '资产类型',
  Manager: '负责人',
  Units: '单元数',
  'Occupancy %': '出租率 %',
  'Asking Price': '挂牌价',
  Territory: '负责区域',
  'Capacity Score': '容量评分',
  'Lead Name': '线索名称',
  Property: '资产',
  Advisor: '顾问',
  Source: '来源',
  Budget: '预算',
  'Target Move Date': '目标入住日',
  Lead: '线索',
  'Tour Number': '看房编号',
  'Feedback Score': '反馈评分',
};

const zhOptionLabels: Record<string, string> = {
  Active: '启用',
  Paused: '暂停',
  Retired: '停用',
  Inbound: '入库',
  Outbound: '出库',
  Adjustment: '调整',
  Draft: '草稿',
  Ordered: '已下单',
  Received: '已收货',
  Cancelled: '已取消',
  Pending: '待处理',
  Processing: '处理中',
  Shipped: '已发货',
  High: '高',
  Medium: '中',
  Low: '低',
  Open: '打开',
  'In Progress': '进行中',
  Blocked: '阻塞',
  Done: '完成',
  Approved: '已批准',
  'In Transit': '运输中',
  Scheduled: '已计划',
  Reconciled: '已核对',
  Damage: '破损',
  'Cycle Count Variance': '盘点差异',
  'Return Correction': '退货修正',
  'System Correction': '系统修正',
  'Pending Approval': '待审批',
  Rejected: '已拒绝',
  Review: '待复核',
  Owner: '所有者',
  Manager: '经理',
  Operator: '操作员',
  Viewer: '只读',
  Purchase: '采购',
  'Cycle Count': '盘点',
  Receiving: '收货',
  Replenishment: '补货',
  Forecast: '预测',
  'Exception Review': '异常复核',
  'Policy Help': '政策帮助',
  Waiting: '等待中',
  Resolved: '已解决',
  System: '系统',
  Inventory: '库存',
  Order: '订单',
  Security: '安全',
  Info: '信息',
  Warning: '警告',
  Critical: '严重',
  Strategic: '战略',
  Growth: '增长',
  Renewal: '续约',
  Healthy: '健康',
  Watch: '观察',
  'At Risk': '风险',
  New: '新建',
  'Decision Maker': '决策人',
  Evaluator: '评估人',
  Discovery: '发现',
  Proposal: '方案',
  Negotiation: '谈判',
  Won: '已赢单',
  Lost: '已输单',
  Call: '电话',
  Demo: '演示',
  Email: '邮件',
  Planned: '已规划',
  Completed: '已完成',
  'Follow Up': '需跟进',
  Multifamily: '多户住宅',
  Office: '办公',
  Retail: '零售',
  Industrial: '工业',
  Renovation: '改造中',
  Listed: '已挂牌',
  'Under Contract': '签约中',
  'On Leave': '休假',
  Referral: '转介绍',
  Portal: '门户',
  'Walk In': '到访',
  Partner: '合作方',
  Qualified: '已确认',
  'Tour Scheduled': '已约看',
  Offer: '报价',
  Dormant: '休眠',
  Rescheduled: '已改期',
};

function localizeLabel(label: string, labels: Record<string, string>, locale: string): string {
  return locale === 'zh-CN' ? (labels[label] ?? label) : label;
}

export function createResources(locale: string): ResourceDefinition[] {
  return resources.map((resource) => ({
    ...resource,
    label: localizeLabel(resource.label, zhResourceLabels, locale),
    group: resource.group ? localizeLabel(resource.group, zhGroupLabels, locale) : resource.group,
    fields: resource.fields.map((field) => ({
      ...field,
      label: localizeLabel(field.label, zhFieldLabels, locale),
      options: field.options?.map((option) => ({
        ...option,
        label: localizeLabel(option.label, zhOptionLabels, locale),
      })),
    })),
  }));
}
